n = input('Digite algo:')
print ('Está em maiúscula? ', n.isupper())
print ('É alfanumérico? ', n.isalnum())
print ('É alfabético', n.isalpha())
print('ascii', n.isascii())
print('É decimal?', n.isdecimal())
print('digit', n.isdigit())
print('identifier', n.isidentifier())
print('Está em minúscula', n.islower())
print('É um número? ', n.isnumeric())
print('printable', n.isprintable())
print('Só tem espaços? ', n.isspace())
print('Está capitalizada? ', n.istitle())